# Generated by Django 4.2.28 on 2026-02-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule_score', models.PositiveIntegerField(default=0)),
                ('api_score', models.PositiveIntegerField(default=0)),
                ('final_score', models.PositiveIntegerField(default=0)),
                ('risk_label', models.CharField(default='Safe', max_length=32)),
                ('issues', models.TextField(blank=True)),
                ('api_verdict', models.CharField(blank=True, max_length=128)),
                ('api_status', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
